### PR TITLE
BRICK-934 - Merge in coreos-vagrant stable channel patch

### PR DESCRIPTION
**Pull request by ahawtho**

### CODE REVIEW

**Comment by ahawtho** [comment]
cc @amattyang

**Comment by ahawtho** [comment]
bricks_setup fails with this set to stable :(  It looks like the ignition config never gets loaded on the stable channel. I'm going to try with beta and see what happens.

**Comment by ahawtho** [comment]
Ok, beta works. I don't understand why stable wouldn't work.

**Review by mordr — APPROVED** [review]

**Comment by mordr** [comment]
Deployed coreos-vagrant successfully using this branch.

**Pull request merged**
